DataSharingApplication/aws_connector/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from image_upload import views

urlpatterns = [
    url(r'^$(?i)',views.login,name='login'),
    path('admin/', admin.site.urls),
    url(r'^uploaddata(?i)/', include('image_upload.urls'))
]

DataSharingApplication/image_upload/urls.py
from django.conf.urls import url
from . import views


app_name='image_upload'

urlpatterns=[
    url(r'^(?i)$',views.login,name='login'),
    url(r'^logout(?i)/$',views.logout,name='logout'),
    url(r'^login(?i)/$',views.login,name='login'),
    url(r'^index(?i)/$',views.index,name='index'),
    url(r'^register(?i)/$',views.rgister,name='register'),
    url(r'^send_to_user(?i)/$',views.send_to_user.as_view(),name='send_to_user'),
    url(r'^delete_from_aws(?i)/$',views.delete_from_aws.as_view(),name='delete_from_aws'),
    url(r'^download(?i)/$',views.download,name='download'),


]

DataSharingApplication/image_upload/models.py
from django.db import models

# Create your models here.
class UserDetails(models.Model):
    # user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=False)
    email = models.CharField(max_length=255,blank=False)
    password = models.CharField(max_length=255, blank=False)
    awsbucketname= models.CharField(max_length=255, blank=False)

class send_recieve_details(models.Model):
    from_user = models.CharField(blank=False,max_length=255)
    to_user = models.CharField(blank=False,max_length=255)
    file_name = models.CharField(max_length=255, blank=True)
    date = models.DateField(default=None, blank=True, null=True)
    link_to_download=models.CharField(max_length=255, blank=True)

# class upload_details(models.Model):
#     from_user = models.ForeignKey(UserDetails, on_delete=models.CASCADE)    
#     file_name = models.CharField(max_length=255, blank=True)
#     date = models.DateField(default=None, blank=True, null=True)

DataSharingApplication/image_upload/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.views import View
from django.shortcuts import redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import boto3,os,json
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.conf import settings
from .s3functions import *
import datetime,re,smtplib 
from .models import UserDetails,send_recieve_details
from awspolicy import BucketPolicy
# Create your views here.
s3=connect()

def rgister(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        email = request.POST['email']
        password = request.POST['password']
        bucketname=str(datetime.datetime.now())
        bucketname=re.sub('[^A-Za-z0-9]+', '', bucketname)
        bucketname=bucketname+firstname.lower()        
        create_bucket(s3,bucketname)
        set_bucket_policy(bucketname)
        user_data=UserDetails()
        user_data.name=firstname
        user_data.email=email
        user_data.password=password
        user_data.awsbucketname=bucketname
        user_data.save()
        return render(request,'image_upload/login.html')
    else: 
        return render(request,'image_upload/register.html')

def logout(request):
    if 'username' in request.session:
        del request.session["username"]
    return render(request,'image_upload/login.html')

def login(request):
    try:
        print(settings.TEMPLATE_DIR)
        if request.method == 'POST':
            username = request.POST['inputEmail']
            password = request.POST['inputPassword']
            userdetails=UserDetails.objects.filter(email=username,password=password)
            if userdetails.exists():
                request.session["username"] = username                
                return HttpResponseRedirect(reverse('image_upload:index'))     
            else:
                 return render(request,'image_upload/login.html')
                           
        else:
            return render(request,'image_upload/login.html')
    except Exception as ex:
        print("error at login",ex)

def index(request):    
    try:
        if 'username' in request.session:  
            userdata=UserDetails.objects.filter(email=request.session['username'])
            awsbucketname=userdata.values('awsbucketname')[0]['awsbucketname']
            if request.method == 'POST' and request.FILES['myfile']:
                myfile = request.FILES['myfile']
                fs = FileSystemStorage()
                # path=r'images\\'+myfile.name
                path=os.path.join("images", myfile.name)
                filename = fs.save(path, myfile)
                filename=upload_intobucket(filename, awsbucketname, myfile.name,s3)
                bucket_items=get_itemsin_bucket(awsbucketname,s3)
                allusers=UserDetails.objects.exclude(email='')
                allusers_email=[]
                for item in allusers:
                    allusers_email.append(item.email)

                count=1
                list_buckt_itm_with_id=[]
                for item in bucket_items:
                    bucket_items_with_id={}
                    bucket_items_with_id={'id':count,'file':item}
                    list_buckt_itm_with_id.append(bucket_items_with_id)
                    count=count+1 

                context = {
                    'bucket_name':awsbucketname,
                    'bucket_items':list_buckt_itm_with_id,
                    'success_upload':True,
                    'username':request.session["username"],
                    'filename':filename,
                    'allusers_email':allusers_email 
                }
                return render(request,'image_upload/index.html',context)
            else:
                allusers=UserDetails.objects.exclude(email='')
                allusers_email=[]
                for item in allusers:
                    allusers_email.append(item.email)              
                
                bucket_items=get_itemsin_bucket(awsbucketname,s3)
                count=1
                list_buckt_itm_with_id=[]
                for item in bucket_items:
                    bucket_items_with_id={}
                    bucket_items_with_id={'id':count,'file':item}
                    list_buckt_itm_with_id.append(bucket_items_with_id)
                    count=count+1                
                context = {
                    'bucket_name':awsbucketname,
                    'bucket_items':list_buckt_itm_with_id,
                    'username':request.session["username"],
                    'success_upload':False   ,
                    'allusers_email':allusers_email 
                }
                return render(request,'image_upload/index.html',context)
        else:
            return render(request,'image_upload/login.html')
    except Exception as ex:
        print("error at index",ex)

class send_to_user(View):
    def post(self, request):
        if 'username' in request.session:
           to_username=request.POST['to_username']
           link=request.POST['link']
           from_user=request.session['username']
           send_recieve_details_obj=send_recieve_details()
           send_recieve_details_obj.from_user=from_user
           send_recieve_details_obj.to_user=to_username
           send_recieve_details_obj.link_to_download=link
           send_recieve_details_obj.file_name=link.split('/')[len(link.split('/'))-1]
           send_recieve_details_obj.date=str(datetime.datetime.now().date())
           send_recieve_details_obj.save()
        #    send_email(to_username,from_user)

class delete_from_aws(View):
    def post(self, request):
        if 'username' in request.session:
           link=request.POST['link']
           leng=len(link.split(r'/'))
           filename_to_delete= link.split(r'/')[leng-1] 
           bucketname= link.split(r'/')[leng-2]      
           print(filename_to_delete) 
           print(bucketname)
           s3.Object(bucketname, filename_to_delete).delete()


def download(request):
    if 'username' in request.session:
        received_data=send_recieve_details.objects.filter(to_user=request.session["username"] )
        # if alluser.exists():

        context = {                    
                    'username':request.session["username"],
                    'received_data':received_data            
                }
        return render(request,'image_upload/download.html',context)
    else:
        return render(request,'image_upload/login.html')


def send_email(TO,fromm):
    print(TO)
    print(fromm)
    gmail_user = "XXXX"
    gmail_pwd = "XXXX"
    TEXT = "Testing sending mail using gmail servers"
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.ehlo()
    server.starttls()
    server.login(gmail_user, gmail_pwd)
    SUBJECT="AWS File sharing system"
    BODY = 'Greetings from data sharing application,'+fromm+' has shared data with you.please login to your account to download the same'
    message ='Subject: {}\n\n{}'.format(SUBJECT, BODY)
    server.sendmail(gmail_user, [TO], message)
    print ('email sent')


if __name__ == "__main__": 
    print('')
    # send_email()

DataSharingApplication/templates/image_upload/Login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<style>/*
        * Specific styles of signin component
        */
       /*
        * General styles
        */
       body, html {
           height: 100%;
           background-repeat: no-repeat;
           background-image: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));
       }
       
       .card-container.card {
           max-width: 350px;
           padding: 40px 40px;
       }
       
       .btn {
           font-weight: 700;
           height: 36px;
           -moz-user-select: none;
           -webkit-user-select: none;
           user-select: none;
           cursor: default;
       }
       
       /*
        * Card component
        */
       .card {
           background-color: #F7F7F7;
           /* just in case there no content*/
           padding: 20px 25px 30px;
           margin: 0 auto 25px;
           margin-top: 50px;
           /* shadows and rounded borders */
           -moz-border-radius: 2px;
           -webkit-border-radius: 2px;
           border-radius: 2px;
           -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
           -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
           box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
       }
       
       .profile-img-card {
           width: 96px;
           height: 96px;
           margin: 0 auto 10px;
           display: block;
           -moz-border-radius: 50%;
           -webkit-border-radius: 50%;
           border-radius: 50%;
       }
       
       /*
        * Form styles
        */
       .profile-name-card {
           font-size: 16px;
           font-weight: bold;
           text-align: center;
           margin: 10px 0 0;
           min-height: 1em;
       }
       
       .reauth-email {
           display: block;
           color: #404040;
           line-height: 2;
           margin-bottom: 10px;
           font-size: 14px;
           text-align: center;
           overflow: hidden;
           text-overflow: ellipsis;
           white-space: nowrap;
           -moz-box-sizing: border-box;
           -webkit-box-sizing: border-box;
           box-sizing: border-box;
       }
       
       .form-signin #inputEmail,
       .form-signin #inputPassword {
           direction: ltr;
           height: 44px;
           font-size: 16px;
       }
       
       .form-signin input[type=email],
       .form-signin input[type=password],
       .form-signin input[type=text],
       .form-signin button {
           width: 100%;
           display: block;
           margin-bottom: 10px;
           z-index: 1;
           position: relative;
           -moz-box-sizing: border-box;
           -webkit-box-sizing: border-box;
           box-sizing: border-box;
       }
       
       .form-signin .form-control:focus {
           border-color: rgb(104, 145, 162);
           outline: 0;
           -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
           box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
       }
       
       .btn.btn-signin {
           /*background-color: #4d90fe; */
           background-color: rgb(104, 145, 162);
           /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
           padding: 0px;
           font-weight: 700;
           font-size: 14px;
           height: 36px;
           -moz-border-radius: 3px;
           -webkit-border-radius: 3px;
           border-radius: 3px;
           border: none;
           -o-transition: all 0.218s;
           -moz-transition: all 0.218s;
           -webkit-transition: all 0.218s;
           transition: all 0.218s;
       }
       
       .btn.btn-signin:hover,
       .btn.btn-signin:active,
       .btn.btn-signin:focus {
           background-color: rgb(12, 97, 33);
       }
       
       .forgot-password {
           color: rgb(104, 145, 162);
       }
       
       .forgot-password:hover,
       .forgot-password:active,
       .forgot-password:focus{
           color: rgb(12, 97, 33);
       }</style>
</head>
<body>
    <div class="container">
        <div class="card card-container">
           <center><label><b>Login</b></label></center> 
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
            <form action="{% url 'image_upload:login' %}" method="POST" >
                {% csrf_token %}
                <span id="reauth-email" class="reauth-email"></span>
                <input type="email" name="inputEmail" class="form-control" placeholder="User Name" required autofocus>
               <br/> <input type="password" name="inputPassword" class="form-control" placeholder="Password" required>
                <div id="remember" class="checkbox">
                    <label>
                        <input type="checkbox" value="remember-me"> Remember me
                    </label>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
            </form><!-- /form -->
            <a class="forgot-password">
                Forgot the password?
            </a>
            <a  href="{% url 'image_upload:register' %}"  class="forgot-password">
                Register
            </a>
        </div><!-- /card-container -->
    </div><!-- /container -->
</body>
</html>
    <script>

            $( document ).ready(function() {
                // DOM ready
            
                // Test data
                /*
                 * To test the script you should discomment the function
                 * testLocalStorageData and refresh the page. The function
                 * will load some test data and the loadProfile
                 * will do the changes in the UI
                 */
                // testLocalStorageData();
                // Load profile if it exits
                loadProfile();
            });
           function getLocalProfile(callback){
               var profileImgSrc      = localStorage.getItem("PROFILE_IMG_SRC");
               var profileName        = localStorage.getItem("PROFILE_NAME");
               var profileReAuthEmail = localStorage.getItem("PROFILE_REAUTH_EMAIL");
           
               if(profileName !== null
                       && profileReAuthEmail !== null
                       && profileImgSrc !== null) {
                   callback(profileImgSrc, profileName, profileReAuthEmail);
               }
           }
           
           /**
            * Main function that load the profile if exists
            * in localstorage
            */
           function loadProfile() {
               if(!supportsHTML5Storage()) { return false; }
               // we have to provide to the callback the basic
               // information to set the profile
               getLocalProfile(function(profileImgSrc, profileName, profileReAuthEmail) {
                   //changes in the UI
                   $("#profile-img").attr("src",profileImgSrc);
                   $("#profile-name").html(profileName);
                   $("#reauth-email").html(profileReAuthEmail);
                   $("#inputEmail").hide();
                   $("#remember").hide();
               });
           }
           
           /**
            * function that checks if the browser supports HTML5
            * local storage
            *
            * @returns {boolean}
            */
           function supportsHTML5Storage() {
               try {
                   return 'localStorage' in window && window['localStorage'] !== null;
               } catch (e) {
                   return false;
               }
           }
           
           /**
            * Test data. This data will be safe by the web app
            * in the first successful login of a auth user.
            * To Test the scripts, delete the localstorage data
            * and comment this call.
            *
            * @returns {boolean}
            */
           function testLocalStorageData() {
               if(!supportsHTML5Storage()) { return false; }
               localStorage.setItem("PROFILE_IMG_SRC", "//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" );
               localStorage.setItem("PROFILE_NAME", "César Izquierdo Tello");
               localStorage.setItem("PROFILE_REAUTH_EMAIL", "oneaccount@gmail.com");
           }

           $(
            function () {
                //$('#Username').focus();
     
                window.location.hash = "n";
                window.location.hash = "A";//again because google chrome don't insert first hash into history
                window.onhashchange = function () { window.location.hash = "n" };
            }
          );

    </script>

DataSharingApplication/templates/image_upload/download.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Cloud Computing Assignment</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
      <style>body {
          font-family: "Helvetica Neue", Helvetica, Arial;
          font-size: 14px;
          line-height: 20px;
          font-weight: 400;
          color: #3b3b3b;
          -webkit-font-smoothing: antialiased;
          font-smoothing: antialiased;
          background: #2b2b2b;
        }
        @media screen and (max-width: 580px) {
          body {
            font-size: 16px;
            line-height: 22px;
          }
        }
        
        .wrapper {
          margin: 0 auto;
          padding: 40px;
          max-width: 800px;
        }
        
        .table {
          margin: 0 0 40px 0;
          width: 100%;
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
          display: table;
        }
        @media screen and (max-width: 580px) {
          .table {
            display: block;
          }
        }
        
        .row {
          display: table-row;
          background: #f6f6f6;
        }
        .row:nth-of-type(odd) {
          background: #e9e9e9;
        }
        .row.header {
          font-weight: 900;
          color: #ffffff;
          background: #ea6153;
        }
        .row.green {
          background: #27ae60;
        }
        .row.blue {
          background: #2980b9;
        }
        @media screen and (max-width: 580px) {
          .row {
            padding: 14px 0 7px;
            display: block;
          }
          .row.header {
            padding: 0;
            height: 6px;
          }
          .row.header .cell {
            display: none;
          }
          .row .cell {
            margin-bottom: 10px;
          }
          .row .cell:before {
            margin-bottom: 3px;
            content: attr(data-title);
            min-width: 98px;
            font-size: 10px;
            line-height: 10px;
            font-weight: bold;
            text-transform: uppercase;
            color: #969696;
            display: block;
          }
        }
        
        .cell {
          padding: 6px 12px;
          display: table-cell;
        }
        @media screen and (max-width: 580px) {
          .cell {
            padding: 2px 16px;
            display: block;
          }
        }
        </style>
    </head>
  <body style="background-color:#ecf0f5">
    <input type="hidden" id="successcheck" value={{success_upload}}>
    <nav class="navbar navbar-default navbar-static-top" style="background-color:#3c8dbc;color: #f4f8f9">      
        <ul class="nav navbar-nav pull-right">
            <li ><a class="navbar-brand" style="color:#f4f8f9"><b>{{username}}&nbsp;<i class="fa fa fa-user"></i></b></a></li>
            <li ><a class="navbar-brand" href="{% url 'image_upload:index' %}" style="color:#f4f8f9"><b>Home&nbsp;<i class="fa fa fa-cloud"></i></b></a></li>
            <li ><a class="navbar-brand" href="{% url 'image_upload:download' %}" style="color:#f4f8f9"><b>Recieved Data&nbsp;<i class="fa fa fa-download""></i></b></a></li>
           <li ><a class="navbar-brand" href="{% url 'image_upload:logout' %}" style="color:#f4f8f9"><b>Logout&nbsp;<i class="fa fa fa-sign-out"></i></b></a></li>             
          </ul>   
    </nav> 
    <div class="container" >
        <div class="jumbotron" style="background-color:#aec7c3">
                <center><h3 style="margin-top: -15px"><b>Received Data</b></h3></center>
                <div style="margin-top: -40px" class="wrapper">  
                    <div class="table">
                      <div class="row header blue">
                        <div class="cell">
                          Data
                        </div>
                        <div class="cell">
                          Recieved From
                        </div>
                        <div class="cell">
                          Date
                        </div>
                        <div class="cell">
                            Download
                          </div>
                      </div>
                      {% for item in received_data %}     
                      <div class="row">
                          <div class="cell" data-title="Name">
                              {{item.file_name}}
                          </div>
                          <div class="cell" data-title="Name" style="width:30%">
                                {{item.from_user}}
                          </div>
                          <div style="width:30%" class="cell" data-title="Name">{{item.date}}</div>
                          <div class="cell" data-title="Name"><a href='{{item.link_to_download}}'  value="Download">Download</a></div>
                        </div>
                      {% endfor %}
                    </div>
                  </div>
        </div>
    </div>
</body>
</html>

DataSharingApplication/templates/image_upload/register.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
body, html {
    height: 100%;
    background-repeat: no-repeat;
    background-image: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));
    padding-top:30px;
}
fieldset {
    border: thin solid #ccc; 
    border-radius: 4px;
    padding: 20px;
    padding-left: 40px;
    background: #fbfbfb;
}
legend {
   color: #678;
}
.form-control {
    width: 95%;
}
label small {
    color: #678 !important;
}
span.req {
    color:maroon;
    font-size: 112%;
}</style>
<div class="container" style="width:600px; margin:0 auto;">
	<div class="row">
        <div class="col-md-12">
            <form class="form-horizontal" method="post" action="#">
                {% csrf_token %}
            <fieldset>

            <center><b>Register</b></center>
            <div class="form-group"> 	 
                <label for="firstname"><span class="req">* </span> Name: </label>
                    <input class="form-control" type="text" name="firstname" id = "txt" onkeyup = "Validate(this)" required /> 
                        <div id="errFirst"></div>    
            </div>


            <div class="form-group">
                <label for="email"><span class="req">* </span> Email Address: </label> 
                    <input class="form-control" required type="text" name="email" id = "email"  onchange="email_validate(this.value);" />   
                        <div class="status" id="status"></div>
            </div>

          

            <div class="form-group">
                <label for="password"><span class="req">* </span> Password: </label>
                    <input required name="password" type="password" class="form-control inputpass" minlength="4" maxlength="16"  id="pass1" /> </p>

                <label for="password"><span class="req">* </span> Password Confirm: </label>
                    <input required name="password" type="password" class="form-control inputpass" minlength="4" maxlength="16" placeholder="Enter again to validate"  id="pass2" onkeyup="checkPass(); return false;" />
                        <span id="confirmMessage" class="confirmMessage"></span>
            </div>

            <div class="form-group">
            
                <?php //$date_entered = date('m/d/Y H:i:s'); ?>
                <input type="hidden" value="<?php //echo $date_entered; ?>" name="dateregistered">
                <input type="hidden" value="0" name="activate" />
                <hr>

                <input type="checkbox" required name="terms" onchange="this.setCustomValidity(validity.valueMissing ? 'Please indicate that you accept the Terms and Conditions' : '');" id="field_terms">   <label for="terms">I agree with the <a href="" title="You may read our terms and conditions by clicking on this link">terms and conditions</a> for Registration.</label><span class="req">* </span>
            </div>

            <div class="form-group row">
                <input class="btn btn-success" type="submit" name="submit_reg" value="Register">
                <a style="margin-right:5%" class="pull-right" href="{% url 'image_upload:login' %}">Login</a>
            </div>
            <span>
               
            </span>
                   

            </fieldset>
            </form><!-- ends register form -->

<script type="text/javascript">
  document.getElementById("field_terms").setCustomValidity("Please indicate that you accept the Terms and Conditions");

  function checkPass()
  {
      //Store the password field objects into variables ...
      var pass1 = document.getElementById('pass1');
      var pass2 = document.getElementById('pass2');
      //Store the Confimation Message Object ...
      var message = document.getElementById('confirmMessage');
      //Set the colors we will be using ...
      var goodColor = "#66cc66";
      var badColor = "#ff6666";
      //Compare the values in the password field 
      //and the confirmation field
      if(pass1.value == pass2.value){
          //The passwords match. 
          //Set the color to the good color and inform
          //the user that they have entered the correct password 
          pass2.style.backgroundColor = goodColor;
          message.style.color = goodColor;
          message.innerHTML = "Passwords Match"
      }else{
          //The passwords do not match.
          //Set the color to the bad color and
          //notify the user.
          pass2.style.backgroundColor = badColor;
          message.style.color = badColor;
          message.innerHTML = "Passwords Do Not Match!"
      }
  } 
  function validatephone(phone) 
  {
      var maintainplus = '';
      var numval = phone.value
      if ( numval.charAt(0)=='+' )
      {
          var maintainplus = '';
      }
      curphonevar = numval.replace(/[\\A-Za-z!"£$%^&\,*+_={};:'@#~,.Š\/<>?|`¬\]\[]/g,'');
      phone.value = maintainplus + curphonevar;
      var maintainplus = '';
      phone.focus;
  }
  // validates text only
  function Validate(txt) {
      txt.value = txt.value.replace(/[^a-zA-Z-'\n\r.]+/g, '');
  }
  // validate email
  function email_validate(email)
  {
  var regMail = /^([_a-zA-Z0-9-]+)(\.[_a-zA-Z0-9-]+)*@([a-zA-Z0-9-]+\.)+([a-zA-Z]{2,3})$/;
  
      if(regMail.test(email) == false)
      {
      document.getElementById("status").innerHTML    = "<span class='warning'>Email address is not valid yet.</span>";
      }
      else
      {
      document.getElementById("status").innerHTML	= "<span class='valid'>Thanks, you have entered a valid Email address!</span>";	
      }
  }
  // validate date of birth
  function dob_validate(dob)
  {
  var regDOB = /^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})$/;
  
      if(regDOB.test(dob) == false)
      {
      document.getElementById("statusDOB").innerHTML	= "<span class='warning'>DOB is only used to verify your age.</span>";
      }
      else
      {
      document.getElementById("statusDOB").innerHTML	= "<span class='valid'>Thanks, you have entered a valid DOB!</span>";	
      }
  }
  // validate address
  function add_validate(address)
  {
  var regAdd = /^(?=.*\d)[a-zA-Z\s\d\/]+$/;
    
      if(regAdd.test(address) == false)
      {
      document.getElementById("statusAdd").innerHTML	= "<span class='warning'>Address is not valid yet.</span>";
      }
      else
      {
      document.getElementById("statusAdd").innerHTML	= "<span class='valid'>Thanks, Address looks valid!</span>";	
      }
  }
  

</script>